### ISSUE TITLE
issue: Tooltips are clipped on constrained containers and `ExternalLink` tooltip disappears when hovering over it

### ISSUE THREAD

**Issue by tigerros** [marc2332/freya#412]
- `Tooltip` component overflow is clipped, which is unwanted behavior when it comes to tooltips. Bug in question:

  ![image](https://github.com/marc2332/freya/assets/76173380/35b7624c-6a8b-499e-9f82-dab944edd17a)

  The red lines are the padding of the black rectangle, inside of which is the `ExternalLink` (which uses tooltips).
- The `ExternalLink` tooltips disappear when user moves their mouse to the tooltip. Very annoying. Also present in #411

**Comment by marc2332** [comment]
Weird, I thought I already fixed that, I'll take a look asap!

**Comment by marc2332** [comment]
> Tooltip component overflow is clipped, which is unwanted behavior when it comes to tooltips. Bug in question:

Mmm, I am sorry but, what is the bug? I don't understand what exactly is being clipped

**Comment by marc2332** [comment]
Ahh, I see, well, I guess that's a case I did not test.

The problem is that the tooltip doesn't have any space left. I think I could fix this by implementing viewport size units, this way I could use e.g 100vw (100% of the window width) in [here](https://github.com/marc2332/freya/blob/1201e569db7625e1c5f84e4e271d4753f9323974/crates/components/src/external_link.rs#L83), this way the Tooltip would have available space to render (It would still just take whatever size it needs, not the whole window width)

**Comment by tigerros** [comment]
Could the position be absolute and be set to the cursor's position? Wouldn't the tooltip ignore constraints that way?

**Comment by marc2332** [comment]
> Could the position be absolute and be set to the cursor's position? Wouldn't the tooltip ignore constraints that way?

Nope, Skia requires you to pass always a width when creating text (it makes sense, it needs to know whether to break line, etc), and Freya, even when using absolute mode, you are still constrained by your parent sizing
