### ISSUE TITLE
enhancement: IME Support

### ISSUE THREAD

**Issue by marc2332** [marc2332/freya#457]

**Comment by CryZe** [comment]
Is this part of 0.2.2? At least on Windows I see no indication of any IME support. Neither the Emoji IME, nor the "legacy" Korean IME, nor the interactive Korean IME are working at all.

**Comment by marc2332** [comment]
> Is this part of 0.2.2? At least on Windows I see no indication of any IME support. Neither the Emoji IME, nor the "legacy" Korean IME, nor the interactive Korean IME are working at all.

I have made some improvements along the way since 0.2.2 was relased, could you try with `0.3.0-rc.0` ?

**Comment by CryZe** [comment]
Thanks for the quick reply. Took a bit longer to try it because apparently it requires the very latest update of Visual Studio 2022 (not just 2022 itself). The situation is looking much better with emoji IME working and it technically even using the Korean interactive IME. Unforunately, it only technically uses it because the interactive states are not being rendered at all.

**Comment by marc2332** [comment]
> interactive states

I am sorry but what do you mean by `interactive states` ?
